-- DormFlow v3 clean history migration. Run only after schema.sql + seed-members.sql.
begin;
do $$
declare
  v_household uuid; v_aug uuid; v_sep uuid; v_oct uuid; v_nov uuid;
  v_jace uuid; v_kean uuid; v_aerian uuid; v_aexy uuid; v_admin uuid;
  v_exp uuid; v_ob uuid; v_payment uuid; v_account uuid;
begin
  select id into v_household from public.households where slug='20-st-paul';
  if v_household is null then raise exception 'Run seed-members.sql first'; end if;
  select hm.id into v_jace from public.household_members hm join public.profiles p on p.id=hm.profile_id where hm.household_id=v_household and p.display_name='Jace';
  select hm.id into v_kean from public.household_members hm join public.profiles p on p.id=hm.profile_id where hm.household_id=v_household and p.display_name='Kean';
  select hm.id into v_aerian from public.household_members hm join public.profiles p on p.id=hm.profile_id where hm.household_id=v_household and p.display_name='Aerian';
  select hm.id into v_aexy from public.household_members hm join public.profiles p on p.id=hm.profile_id where hm.household_id=v_household and p.display_name='Aexy';
  select hm.id into v_admin from public.household_members hm where hm.household_id=v_household and hm.role='admin' limit 1;
  if v_jace is null or v_kean is null or v_aerian is null or v_aexy is null then raise exception 'All four member links are required'; end if;
  insert into public.billing_periods(household_id,month,status,created_by) values(v_household,'2026-08-01','active',v_admin) on conflict(household_id,month) do update set status='active' returning id into v_aug;
  insert into public.billing_periods(household_id,month,status,created_by) values(v_household,'2026-09-01','draft',v_admin) on conflict(household_id,month) do update set status=public.billing_periods.status returning id into v_sep;
  insert into public.billing_periods(household_id,month,status,created_by) values(v_household,'2026-10-01','draft',v_admin) on conflict(household_id,month) do update set status=public.billing_periods.status returning id into v_oct;
  insert into public.billing_periods(household_id,month,status,created_by) values(v_household,'2026-11-01','draft',v_admin) on conflict(household_id,month) do update set status=public.billing_periods.status returning id into v_nov;
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Housing & Utilities','Rent',1000000,'2026-08-01','2026-08-24','housing','Rent / Landlord','history:bill-6',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,250000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,250000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,250000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,250000);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Housing & Utilities','Water',40200,'2026-08-01','2026-08-09','utility','Water','history:bill-7',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,13400);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,13400);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,13400);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,0);
  insert into public.utility_records(expense_id,utility_type) values(v_exp,'water') on conflict(expense_id) do nothing;
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Housing & Utilities','Meralco',200214,'2026-08-01','2026-08-21','utility','Meralco','history:bill-8',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,66738);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,66738);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,66738);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,0);
  insert into public.utility_records(expense_id,utility_type) values(v_exp,'electricity') on conflict(expense_id) do nothing;
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Housing & Utilities','PLDT Wifi',162500,'2026-08-01','2026-08-25','utility','PLDT Wifi','history:bill-9',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,40625);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,40625);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,40625);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,40625);
  insert into public.utility_records(expense_id,utility_type) values(v_exp,'wifi') on conflict(expense_id) do nothing;
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'PayLater / Loans','SPayLater · Aerian',59200,'2026-08-05','2026-08-05','paylater',null,'history:loan-6',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,14800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,14800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,14800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,14800);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_aerian,59200);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'PayLater / Loans','SPayLater · Aexy',28000,'2026-08-15','2026-08-15','paylater',null,'history:loan-9',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,7000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,7000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,7000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,7000);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_aexy,28000);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'PayLater / Loans','SPayLater · Kean',42800,'2026-08-15','2026-08-15','paylater',null,'history:loan-12',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,11800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,11800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,11800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,11800);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_kean,47200);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'PayLater / Loans','TikTok PayLater · Jace',36000,'2026-08-16','2026-08-16','paylater',null,'history:loan-18',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,9000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,9000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,9000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,9000);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,36000);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Sponge',5000,'2026-08-14','2026-08-14','grocery',null,'history:grocery-6',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,1250);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,1250);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,1250);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,1250);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_kean,5000);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Puregold Groceries',310064,'2026-08-18','2026-08-18','grocery',null,'history:grocery-7',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,77516);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,77516);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,77516);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,77516);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,310064);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Ziplock for Food Storage',10600,'2026-08-18','2026-08-18','grocery',null,'history:grocery-8',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,2650);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,2650);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,2650);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,2650);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,10600);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Sukigrocer',51500,'2026-08-18','2026-08-18','grocery',null,'history:grocery-9',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,12875);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,12875);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,12875);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,12875);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,51500);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Puregold Essentials',67420,'2026-08-19','2026-08-19','grocery',null,'history:grocery-10',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,16855);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,16855);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,16855);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,16855);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,67420);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Egg',27000,'2026-08-20','2026-08-20','grocery',null,'history:grocery-11',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,6750);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,6750);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,6750);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,6750);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_aexy,27000);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Rice and Condiments',53724,'2026-08-25','2026-08-25','grocery',null,'history:grocery-12',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,13431);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,13431);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,13431);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,13431);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,53724);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Groceries',98000,'2026-08-25','2026-08-25','grocery',null,'history:grocery-13',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,49000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,49000);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,0);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,0);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,98000);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Sukigrocer',51600,'2026-08-26','2026-08-26','grocery',null,'history:grocery-14',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,25800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,25800);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,0);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,0);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,51600);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Snacks',80800,'2026-08-28','2026-08-28','grocery',null,'history:grocery-15',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,40400);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,40400);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,0);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,0);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,80800);
  perform public.generate_expense_obligations_v3(v_exp);
  insert into public.expenses(household_id,period_id,category,description,amount_cents,expense_date,due_date,source_type,source_label,idempotency_key,created_by,updated_by) values(v_household,v_aug,'Groceries','Puregold',65400,'2026-08-30','2026-08-30','grocery',null,'history:grocery-16',v_admin,v_admin) on conflict(household_id,idempotency_key) do update set description=excluded.description returning id into v_exp;
  delete from public.expense_payers where expense_id=v_exp; delete from public.expense_splits where expense_id=v_exp; delete from public.obligations where source_expense_id=v_exp;
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_jace,32700);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_kean,32700);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aerian,0);
  insert into public.expense_splits(expense_id,member_id,amount_cents) values(v_exp,v_aexy,0);
  insert into public.expense_payers(expense_id,member_id,amount_cents) values(v_exp,v_jace,65400);
  perform public.generate_expense_obligations_v3(v_exp);
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-6';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_jace and creditor_member_id=v_aerian limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_jace,v_aerian,14800,'2026-08-05T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-6-jace',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,14800) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-6';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_aerian limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_aerian,14800,'2026-08-05T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-6-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,14800) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-6';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_aerian limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_aerian,14800,'2026-08-05T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-6-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,14800) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-9';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_jace and creditor_member_id=v_aexy limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_jace,v_aexy,7000,'2026-08-15T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-9-jace',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,7000) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-9';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_aexy limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_aexy,7000,'2026-08-15T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-9-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,7000) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-9';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_aexy limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_aexy,7000,'2026-08-15T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-9-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,7000) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-12';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_jace and creditor_member_id=v_kean limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_jace,v_kean,11800,'2026-08-15T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-12-jace',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,11800) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-12';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_kean limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_kean,11800,'2026-08-15T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-12-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,11800) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-12';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_kean limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_kean,11800,'2026-08-15T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-12-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,11800) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-18';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_jace,9000,'2026-08-16T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-18-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,9000) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-18';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_jace,9000,'2026-08-16T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-18-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,9000) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:loan-18';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_jace,9000,'2026-08-16T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-loan-18-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,9000) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-6';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_jace and creditor_member_id=v_kean limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_jace,v_kean,1250,'2026-08-14T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-6-jace',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,1250) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-6';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_kean limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_kean,1250,'2026-08-14T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-6-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,1250) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-6';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_kean limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_kean,1250,'2026-08-14T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-6-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,1250) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-7';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_jace,77516,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-7-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,77516) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-7';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_jace,77516,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-7-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,77516) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-7';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_jace,77516,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-7-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,77516) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-8';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_jace,2650,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-8-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,2650) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-8';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_jace,2650,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-8-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,2650) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-8';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_jace,2650,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-8-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,2650) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-9';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_jace,12875,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-9-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,12875) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-9';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_jace,12875,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-9-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,12875) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-9';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_jace,12875,'2026-08-18T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-9-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,12875) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-10';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_jace,16855,'2026-08-19T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-10-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,16855) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-10';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_jace,16855,'2026-08-19T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-10-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,16855) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-10';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aexy and creditor_member_id=v_jace limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aexy,v_jace,16855,'2026-08-19T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-10-aexy',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,16855) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-11';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_jace and creditor_member_id=v_aexy limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_jace,v_aexy,6750,'2026-08-20T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-11-jace',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,6750) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-11';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_kean and creditor_member_id=v_aexy limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_kean,v_aexy,6750,'2026-08-20T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-11-kean',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,6750) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  select id into v_exp from public.expenses where household_id=v_household and idempotency_key='history:grocery-11';
  select id into v_ob from public.obligations where source_expense_id=v_exp and debtor_member_id=v_aerian and creditor_member_id=v_aexy limit 1;
  insert into public.payments(household_id,payer_member_id,payee_member_id,amount_cents,paid_at,method,reference_private,idempotency_key,verified_by) values(v_household,v_aerian,v_aexy,6750,'2026-08-20T12:00:00+08:00','Legacy workbook','','history:legacy-pay-obl-grocery-11-aerian',v_admin) on conflict(household_id,idempotency_key) do update set amount_cents=excluded.amount_cents returning id into v_payment;
  insert into public.payment_allocations(payment_id,obligation_id,amount_cents) values(v_payment,v_ob,6750) on conflict(payment_id,obligation_id) do update set amount_cents=excluded.amount_cents;
  insert into public.paylater_accounts(household_id,provider,borrower_member_id,borrower_label,creditor_member_id,original_total_cents,status) values(v_household,'SPayLater',null,'Legacy borrower not recorded',v_aerian,177600,'active') returning id into v_account;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_aug,'2026-08-05',59200,1,'posted') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_sep,'2026-09-05',59200,2,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_oct,'2026-10-05',59200,3,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_accounts(household_id,provider,borrower_member_id,borrower_label,creditor_member_id,original_total_cents,status) values(v_household,'SPayLater',null,'Legacy borrower not recorded',v_aexy,84000,'active') returning id into v_account;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_aug,'2026-08-15',28000,1,'posted') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_sep,'2026-09-15',28000,2,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_oct,'2026-10-15',28000,3,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_accounts(household_id,provider,borrower_member_id,borrower_label,creditor_member_id,original_total_cents,status) values(v_household,'SPayLater',null,'Legacy borrower not recorded',v_kean,128400,'active') returning id into v_account;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_aug,'2026-08-15',42800,1,'posted') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_sep,'2026-09-15',42800,2,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_oct,'2026-10-15',42800,3,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_accounts(household_id,provider,borrower_member_id,borrower_label,creditor_member_id,original_total_cents,status) values(v_household,'SPayLater',null,'Legacy borrower not recorded',v_jace,1398000,'active') returning id into v_account;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_sep,'2026-09-05',466000,1,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_oct,'2026-10-05',466000,2,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_nov,'2026-11-05',466000,3,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_accounts(household_id,provider,borrower_member_id,borrower_label,creditor_member_id,original_total_cents,status) values(v_household,'TikTok PayLater',null,'Legacy borrower not recorded',v_jace,108000,'active') returning id into v_account;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_aug,'2026-08-16',36000,1,'posted') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_sep,'2026-09-16',36000,2,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
  insert into public.paylater_installments(account_id,period_id,due_date,amount_cents,sequence_no,status) values(v_account,v_oct,'2026-10-16',36000,3,'scheduled') on conflict(account_id,sequence_no) do update set due_date=excluded.due_date,amount_cents=excluded.amount_cents,status=excluded.status;
end $$;
commit;

-- Verification targets
select 'August total obligations' check_name, sum(es.amount_cents)::bigint cents from public.expense_splits es join public.expenses e on e.id=es.expense_id join public.billing_periods bp on bp.id=e.period_id join public.households h on h.id=bp.household_id where h.slug='20-st-paul' and bp.month='2026-08-01';
select 'August outstanding' check_name, sum(ob.outstanding_cents)::bigint cents from public.obligation_balances_v3 ob join public.billing_periods bp on bp.id=ob.period_id join public.households h on h.id=bp.household_id where h.slug='20-st-paul' and bp.month='2026-08-01';
select 'August settled' check_name, 2394422-sum(ob.outstanding_cents)::bigint cents from public.obligation_balances_v3 ob join public.billing_periods bp on bp.id=ob.period_id join public.households h on h.id=bp.household_id where h.slug='20-st-paul' and bp.month='2026-08-01';
-- Expected: 2394422 total, 188193 outstanding, 2206229 settled.
