import {supabase} from './auth.js';
import {formatPeso,escapeHtml} from './read-model-v3.js';
import {icon} from './icons.js';
import {suggestOldest} from './payment-form.js';
import {requestPushForTarget} from './notifications.js';
export async function loadReviewQueue(){return supabase.select('payment_claims','select=id,payer_member_id,payee_member_id,amount_cents,paid_at,method,status,note,suggested_allocations,version,created_at&status=eq.pending&order=created_at.asc');}
export function renderReviewQueue(rows=[]){
  const total=rows.reduce((sum,x)=>sum+Number(x.amount_cents||0),0);
  return `<section class="screen banking-dashboard review-screen"><div class="bank-page-head"><div><span class="screen-kicker">Admin review</span><h1>Review</h1></div><span class="member-status-pill">${rows.length} pending</span></div><section class="review-summary-card"><span class="summary-icon warm">${icon('review')}</span><div><small>Pending claims</small><strong>${rows.length}</strong></div><div><small>Amount awaiting review</small><strong>${formatPeso(total)}</strong></div></section><article class="bank-panel"><div class="panel-head"><div><span>Queue</span><h2>Payment claims</h2></div></div><div class="review-claim-list">${rows.map(c=>`<button class="review-claim-card" data-review-claim="${c.id}" type="button"><span class="activity-icon warm">${icon('receipt')}</span><div><strong>${formatPeso(c.amount_cents)}</strong><small>${escapeHtml(c.method)} · ${new Date(c.paid_at).toLocaleDateString('en-PH')}</small></div><em>Review</em><b>›</b></button>`).join('')||'<div class="empty-state-bank"><strong>Nothing waiting for review</strong><span>New roommate payment claims will appear here.</span></div>'}</div></article></section>`;
}

export async function openClaimReview(claim,{onDone=()=>{}}={}){let allocations=claim.suggested_allocations||[];if(!allocations.length){const rows=await supabase.rpc('open_obligations_v3',{p_debtor:claim.payer_member_id,p_creditor:claim.payee_member_id});allocations=suggestOldest(rows,claim.amount_cents).allocations;}const allocated=allocations.reduce((s,x)=>s+Number(x.amount_cents||0),0),credit=Math.max(0,claim.amount_cents-allocated);const sheet=document.querySelector('#sheet'),content=document.querySelector('#sheet-content');content.innerHTML=`<form class="sheet-body" id="review-form"><div class="sheet-grabber"></div><div class="sheet-head"><h2>Payment claim</h2><button type="button" class="icon-plain" data-close-sheet>×</button></div><div class="review-amount">${formatPeso(claim.amount_cents)}</div><div class="allocation-editor"><span>Apply to</span>${allocations.map((a,i)=>`<label><small>Balance ${i+1}</small><input name="alloc-${i}" inputmode="decimal" value="${(a.amount_cents/100).toFixed(2)}" data-obligation="${a.obligation_id}"></label>`).join('')||'<div class="empty-line">No open obligation match</div>'}</div>${credit?`<div class="metric-line"><span>Keep as credit</span><strong>${formatPeso(credit)}</strong></div>`:''}<label class="field rejection-field" hidden><span>Reason</span><textarea name="reason" rows="2"></textarea></label><div class="review-actions"><button type="button" class="danger-action" data-reject>Reject</button><button type="submit" class="primary-action">Verify & apply</button></div></form>`;sheet.showModal();content.querySelector('[data-close-sheet]').onclick=()=>sheet.close();content.querySelector('[data-reject]').onclick=async()=>{const reason=prompt('Reason for rejection?')||'Not verified';await supabase.rpc('review_payment_claim_v3',{p_claim:claim.id,p_decision:'reject',p_allocations:[],p_rejection_reason:reason,p_idempotency_key:null,p_credit_cents:0});await requestPushForTarget({targetType:'payment_claim',targetId:claim.id});sheet.close();onDone();};content.querySelector('form').onsubmit=async e=>{e.preventDefault();const edited=[...e.currentTarget.querySelectorAll('[data-obligation]')].map(x=>({obligation_id:x.dataset.obligation,amount_cents:Math.round(Number(x.value)*100)})).filter(x=>x.amount_cents>0),sum=edited.reduce((s,x)=>s+x.amount_cents,0),creditCents=Math.max(0,claim.amount_cents-sum);await supabase.rpc('review_payment_claim_v3',{p_claim:claim.id,p_decision:'verify',p_allocations:edited,p_rejection_reason:null,p_idempotency_key:`claim:${claim.id}`,p_credit_cents:creditCents});await requestPushForTarget({targetType:'payment_claim',targetId:claim.id});sheet.close();onDone();};}
