import {supabase} from './auth.js';
import {escapeHtml} from './read-model-v3.js';
import {icon} from './icons.js';
import {requestPushForTarget} from './notifications.js';
export function activeAnnouncement(a,now=Date.now()){if(!a?.is_active)return false;const start=Date.parse(a.starts_at||0);const end=a.ends_at?Date.parse(a.ends_at):Infinity;return start<=now&&now<end;}
export function buildAnnouncementPayload({householdId,title,body,priority='normal',startsAt,endsAt,notifyHousehold=false,actorId}){return {household_id:householdId,title:String(title).trim(),body:String(body).trim(),priority,starts_at:new Date(startsAt).toISOString(),ends_at:endsAt?new Date(endsAt).toISOString():null,is_active:true,notify_household:Boolean(notifyHousehold),created_by:actorId,updated_by:actorId};}
export async function loadActiveAnnouncements(){const now=new Date().toISOString();return supabase.select('announcements',`select=id,title,body,priority,starts_at,ends_at,is_active&is_active=eq.true&starts_at=lte.${encodeURIComponent(now)}&order=priority.desc,created_at.desc`);}
export function renderAnnouncementTicker(rows=[]){
  const active=rows.filter(a=>activeAnnouncement(a));
  if(!active.length)return '';
  const content=active.map(a=>`<span class="ticker-item priority-${a.priority}"><b>${escapeHtml(a.title)}</b><i>${escapeHtml(a.body)}</i></span>`).join('<span class="ticker-sep">•</span>');
  const repeatCount=active.length===1?6:active.length===2?4:3;
  const loop=Array.from({length:repeatCount},()=>content).join('<span class="ticker-sep">•</span>');
  return `<section class="announcement-ticker" aria-label="Household announcements"><div class="ticker-track"><div class="ticker-copy">${loop}</div><div class="ticker-copy" aria-hidden="true">${loop}</div></div></section>`;
}
export async function createAnnouncement(payload){return supabase.rpc('create_announcement_v3',{p_title:payload.title,p_body:payload.body,p_priority:payload.priority,p_starts_at:payload.starts_at,p_ends_at:payload.ends_at,p_notify_household:payload.notify_household});}
export async function loadAdminAnnouncements(){return supabase.select('announcements','select=*&order=is_active.desc,starts_at.desc');}
export function renderAdminAnnouncements(rows=[]){const active=rows.filter(a=>a.is_active).length;return `<section class="screen banking-dashboard announcements-screen"><div class="bank-page-head"><div><span class="screen-kicker">Household updates</span><h1>Announcements</h1></div><button class="mode-switch-card compact-mode" data-admin-add="announcement" type="button"><span>${icon('announcement')}</span><div><strong>Post</strong><small>Notify the household</small></div><b>›</b></button></div><section class="review-summary-card announcement-summary"><span class="summary-icon warm">${icon('announcement')}</span><div><small>Active</small><strong>${active}</strong></div><div><small>Total posts</small><strong>${rows.length}</strong></div></section><div class="announcement-card-list">${rows.map(a=>`<article class="announcement-bank-card priority-${escapeHtml(a.priority)}"><span class="announcement-card-icon">${icon('announcement')}</span><div><strong>${escapeHtml(a.title)}</strong><small>${escapeHtml(a.priority)} · ${a.is_active?'Active':'Inactive'}</small></div><div class="record-actions"><button data-announcement-edit="${a.id}">Edit</button><button data-announcement-toggle="${a.id}" data-active="${a.is_active}">${a.is_active?'Deactivate':'Activate'}</button></div></article>`).join('')||'<div class="empty-state-bank"><strong>No announcements</strong><span>Post household updates from here.</span></div>'}</div></section>`;}
export async function openAnnouncementSheet({identity,onDone=()=>{},existing=null}){const sheet=document.querySelector('#sheet'),content=document.querySelector('#sheet-content');const local=iso=>iso?new Date(new Date(iso).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';content.innerHTML=`<form id="announcement-form" class="sheet-body"><div class="sheet-grabber"></div><div class="sheet-head"><h2>${existing?'Edit':'Announcement'}</h2><button class="icon-plain" data-close-sheet type="button">×</button></div><label class="field"><span>Title</span><input name="title" maxlength="120" value="${escapeHtml(existing?.title||'')}" required></label><label class="field"><span>Message</span><textarea name="body" rows="3" maxlength="1000" required>${escapeHtml(existing?.body||'')}</textarea></label><label class="field"><span>Priority</span><select name="priority"><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label><label class="field"><span>Starts</span><input name="startsAt" type="datetime-local" value="${local(existing?.starts_at)||new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}" required></label><label class="field"><span>Ends <small>optional</small></span><input name="endsAt" type="datetime-local" value="${local(existing?.ends_at)}"></label><label class="check-row"><input name="notify" type="checkbox" ${existing?.notify_household?'checked':''}><span>Notify household</span></label><button class="primary-action" type="submit">${existing?'Save':'Post announcement'}</button></form>`;sheet.showModal();content.querySelector('[data-close-sheet]').onclick=()=>sheet.close();const form=content.querySelector('form');if(existing)form.priority.value=existing.priority;form.onsubmit=async e=>{e.preventDefault();const d=new FormData(form);const payload=buildAnnouncementPayload({householdId:identity.householdId||identity.household_id,title:d.get('title'),body:d.get('body'),priority:d.get('priority'),startsAt:d.get('startsAt'),endsAt:d.get('endsAt'),notifyHousehold:d.get('notify')==='on',actorId:identity.memberId||identity.member_id});if(existing)await supabase.update('announcements',`id=eq.${existing.id}`,{...payload,created_by:existing.created_by,updated_at:new Date().toISOString()});else{const announcementId=await createAnnouncement(payload);if(payload.notify_household)await requestPushForTarget({targetType:'announcement',targetId:announcementId});}sheet.close();onDone();};}
