import {supabase} from './auth.js';

export const HOUSEHOLD_MEDIA_BUCKET='household-media';
export const MAX_MEDIA_BYTES=5*1024*1024;
export const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp']);
const avatarCache=new Map();
export function invalidateAvatar(identityOrProfileId){const id=typeof identityOrProfileId==='string'?identityOrProfileId:idOf(identityOrProfileId,'profileId');if(id)avatarCache.delete(id);}

function idOf(identity,key){return identity?.[key]||identity?.[key.replace(/[A-Z]/g,m=>'_'+m.toLowerCase())];}
function extFor(file){if(file.type==='image/png')return 'png';if(file.type==='image/webp')return 'webp';return 'jpg';}
function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;}
export function validateHouseholdImage(file){if(!file)throw new Error('Choose an image first.');if(!IMAGE_TYPES.has(file.type))throw new Error('Use a JPG, PNG, or WebP image.');if(Number(file.size)>MAX_MEDIA_BYTES)throw new Error('Image must be 5 MB or smaller.');return file;}
export async function signedHouseholdMediaUrl(path,expiresIn=900){if(!path)return '';const signed=await supabase.createSignedUrl(HOUSEHOLD_MEDIA_BUCKET,path,expiresIn);return signed.signedURL||signed.signedUrl||'';}
export async function resolveAvatar(identity,{force=false}={}){const profileId=idOf(identity,'profileId');if(!profileId)return {path:null,url:''};const cached=avatarCache.get(profileId);if(!force&&cached&&cached.expiresAt>Date.now())return {path:cached.path,url:cached.url};const rows=await supabase.select('profiles',`select=avatar_path&id=eq.${profileId}&limit=1`);const path=rows[0]?.avatar_path||null,url=path?await signedHouseholdMediaUrl(path):'';avatarCache.set(profileId,{path,url,expiresAt:Date.now()+12*60*1000});return {path,url};}
export async function uploadAvatar(identity,file,{oldPath=null}={}){validateHouseholdImage(file);const householdId=idOf(identity,'householdId'),memberId=idOf(identity,'memberId'),profileId=idOf(identity,'profileId');const path=`${householdId}/profiles/${memberId}/avatar/${uid()}-photo.${extFor(file)}`;await supabase.upload(HOUSEHOLD_MEDIA_BUCKET,path,file);try{await supabase.update('profiles',`id=eq.${profileId}`,{avatar_path:path,updated_at:new Date().toISOString()});}catch(err){await supabase.removeStorageObject(HOUSEHOLD_MEDIA_BUCKET,path).catch(()=>{});throw err;}if(oldPath&&oldPath!==path)await supabase.removeStorageObject(HOUSEHOLD_MEDIA_BUCKET,oldPath).catch(()=>{});invalidateAvatar(identity);const url=await signedHouseholdMediaUrl(path);avatarCache.set(profileId,{path,url,expiresAt:Date.now()+12*60*1000});return {path,url};}
export async function removeAvatar(identity,oldPath){const profileId=idOf(identity,'profileId');await supabase.update('profiles',`id=eq.${profileId}`,{avatar_path:null,updated_at:new Date().toISOString()});if(oldPath)await supabase.removeStorageObject(HOUSEHOLD_MEDIA_BUCKET,oldPath).catch(()=>{});invalidateAvatar(identity);return true;}
export async function loadPaymentAttachment(attachmentId){if(!attachmentId)return null;const rows=await supabase.select('attachments',`select=id,bucket,object_path,mime_type,file_size& id=eq.${attachmentId}`.replace('& ', '&'));const row=rows[0];if(!row)return null;return {...row,url:await signedHouseholdMediaUrl(row.object_path)};}
export async function uploadPaymentQr(identity,paymentMethodId,file,{oldAttachment=null,targetMemberId=null}={}){validateHouseholdImage(file);const householdId=idOf(identity,'householdId'),ownerMemberId=targetMemberId||idOf(identity,'memberId');const path=`${householdId}/payment-profiles/${ownerMemberId}/qr/${uid()}-qr.${extFor(file)}`;await supabase.upload(HOUSEHOLD_MEDIA_BUCKET,path,file);let attachment;try{const rows=await supabase.insert('attachments',{household_id:householdId,owner_member_id:ownerMemberId,parent_type:'payment_profile',parent_id:paymentMethodId,bucket:HOUSEHOLD_MEDIA_BUCKET,object_path:path,mime_type:file.type,file_size:file.size,created_by:idOf(identity,'memberId')});attachment=rows[0];await supabase.update('member_payment_methods',`id=eq.${paymentMethodId}`,{qr_attachment_id:attachment.id,updated_at:new Date().toISOString()});}catch(err){await supabase.removeStorageObject(HOUSEHOLD_MEDIA_BUCKET,path).catch(()=>{});if(attachment?.id)await supabase.remove('attachments',`id=eq.${attachment.id}`).catch(()=>{});throw err;}if(oldAttachment?.object_path)await supabase.removeStorageObject(HOUSEHOLD_MEDIA_BUCKET,oldAttachment.object_path).catch(()=>{});if(oldAttachment?.id)await supabase.remove('attachments',`id=eq.${oldAttachment.id}`).catch(()=>{});return {...attachment,url:await signedHouseholdMediaUrl(path)};}
export async function removePaymentQr(paymentMethodId,attachment){await supabase.update('member_payment_methods',`id=eq.${paymentMethodId}`,{qr_attachment_id:null,updated_at:new Date().toISOString()});if(attachment?.object_path)await supabase.removeStorageObject(HOUSEHOLD_MEDIA_BUCKET,attachment.object_path).catch(()=>{});if(attachment?.id)await supabase.remove('attachments',`id=eq.${attachment.id}`).catch(()=>{});return true;}
