import {supabase} from './auth.js';
import {normalizeInstallmentSchedule} from './people-settings.js';
import {parseMoneyCents} from './admin-actions.js';
import {formatPeso,escapeHtml} from './read-model-v3.js';
import {icon} from './icons.js';
export async function loadPayLater(){return supabase.select('paylater_accounts','select=id,provider,borrower_member_id,borrower_label,creditor_member_id,original_total_cents,status,paylater_installments(id,due_date,amount_cents,sequence_no,status)&order=created_at.desc');}
export function renderPayLater(rows=[]){
  const total=rows.reduce((sum,a)=>sum+Number(a.original_total_cents||0),0),upcoming=rows.reduce((sum,a)=>sum+(a.paylater_installments?.filter(x=>x.status==='scheduled').length||0),0);
  return `<section class="screen banking-dashboard paylater-screen"><div class="bank-page-head"><div><span class="screen-kicker">Installments</span><h1>PayLater</h1></div><span class="member-status-pill">${upcoming} upcoming</span></div><section class="payments-hero-card paylater-hero"><div><span>Active schedules</span><strong>${formatPeso(total)}</strong><small>${rows.length} ${rows.length===1?'account':'accounts'}</small></div><span class="summary-icon warm">${icon('paylater')}</span></section><div class="paylater-card-grid">${rows.map(a=>{const scheduled=a.paylater_installments?.filter(x=>x.status==='scheduled')||[],next=[...scheduled].sort((x,y)=>String(x.due_date).localeCompare(String(y.due_date)))[0];return `<article class="paylater-bank-card"><div class="paylater-card-head"><span>${icon('paylater')}</span><div><strong>${escapeHtml(a.provider)}</strong><small>${escapeHtml(a.borrower_label||'Household schedule')}</small></div><em>${escapeHtml(a.status||'active')}</em></div><div class="paylater-card-amount"><small>Original total</small><strong>${formatPeso(a.original_total_cents)}</strong></div><div class="paylater-card-foot"><span>${scheduled.length} upcoming</span><b>${next?`Next ${new Date(next.due_date+'T00:00:00').toLocaleDateString('en-PH',{month:'short',day:'numeric'})}`:'No scheduled installment'}</b></div></article>`}).join('')||'<div class="empty-state-bank"><strong>No PayLater schedules</strong><span>Installments will appear here once added.</span></div>'}</div></section>`;
}

export async function openPayLaterSheet({identity,onDone=()=>{}}){const members=await supabase.select('household_members','select=id,profiles(display_name)&is_active=eq.true');const sheet=document.querySelector('#sheet'),content=document.querySelector('#sheet-content');content.innerHTML=`<form class="sheet-body" id="paylater-form"><div class="sheet-grabber"></div><div class="sheet-head"><h2>PayLater</h2><button type="button" class="icon-plain" data-close-sheet>×</button></div><label class="field"><span>Provider</span><input name="provider" value="SPayLater" required></label><label class="field"><span>Borrower</span><select name="borrower">${members.map(m=>`<option value="${m.id}">${escapeHtml(m.profiles?.display_name||'Member')}</option>`).join('')}</select></label><label class="field amount-field"><span>Total</span><input name="amount" inputmode="decimal" required></label><label class="field"><span>Installments</span><input name="count" type="number" min="1" max="24" value="3" required></label><label class="field"><span>First due date</span><input name="firstDue" type="date" required></label><button class="primary-action" type="submit">Create schedule</button></form>`;sheet.showModal();content.querySelector('[data-close-sheet]').onclick=()=>sheet.close();content.querySelector('form').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget),total=parseMoneyCents(d.get('amount')),schedule=normalizeInstallmentSchedule(total,Number(d.get('count')),d.get('firstDue'));await supabase.rpc('create_paylater_v3',{p_provider:d.get('provider'),p_borrower:(d.get('borrower')),p_total_cents:total,p_schedule:schedule});sheet.close();onDone();};}
